#大型项目的编译环境室友不同makefile构成的
#编译环境设计需求依据项目的整体架构设计
#整个项目的编译过程可以分解为不同的阶段
#根据不同的阶段有针对性的对makefile进行设计
#makefile也需要考虑复用性和维护性等基本程序特性，因为makefile也是程序
#要么不写代码，写就要写最好的代码！

include pro-cfg.mk
include cmd-cfg.mk
include pro-rule.mk