# $@ 当前规则中触发命令被执行的目标

# $^ 当前规则中的所有依赖

# $< 当前规则中的第一个依赖

.PHONY : test1 test2

NENUCL := NENU CHEN LEI



test1 : 
	@echo "$(MAKE_VERSION)"
	@echo "$(CURDIR)"
	@echo "$(.VARIABLES)"
test2 :
	@echo "$(RM)"
