# 条件判断句之前可以有空格，但是不能有Tab字符，也就是制表符
# 在条件语句中不要使用自动变量（$@、$^、$<）
# 一条完整的的条件语句必须位于同一个makefile中，不要在a这个makefile中写一部分，然后跑到b这个makefile中写一部分
# 条件判断类似C语言中的宏，预处理阶段有效，执行阶段无效
# make在加载makefile时，首先计算表达式的值（赋值方式不同，计算方式不同），根据判断语句的表达式决定执行的内容

.PHONY : test

var1 := A
var2 := $(var1)
var3 := 

test :
    ifeq ($(var2),$(var1))
		@echo "var1 == var2"
    else
		@echo "var1 != var2"
    endif

    ifneq ($(var2),)
		@echo "var2 is not empty"
    else
		@echo "var2 is empty"
    endif

    ifdef var2
		@echo "var3 is not empty"
    else
		@echo "var3 is empty"
    endif

    ifndef var3
		@echo "var3 is empty"
    else
		@echo "var3 is not empty"
    endif		
