
var := NenuPhysics
new := ChenLei

test : var := test-var
%le : override new := test-new


test: another
	@echo "test :"
	@echo "var => $(var)"
	@echo "new => $(new)"

another:	
	@echo "another :"
	@echo "var => $(var)"
	@echo "new => $(new)"

rule :
	@echo "rule :"
	@echo "var => $(var)"
	@echo "new => $(new)"
